
module.exports={
    gettypeData(){
        let data={
            "goodsList":[
                {
                    "title":"男装",
                    "content":{
                        "smallTitle":"男装",
                        "clothes":[
                            {
                                "ctitle":"男士外套",
                                "ccontent":[
                                    {
                                        "img":"static/2 (14).jpg",
                                        "title":"羽绒/棉服"
                                    },
                                    {
                                        "img":"static/2 (5).jpg",
                                        "title":"皮衣/夹克"
                                    },
                                    {
                                        "img":"static/2 (11).jpg",
                                        "title":"风衣/大衣"
                                    },
                                    {
                                        "img":"static/2 (7).jpg",
                                        "title":"西服套装"
                                    },
                                ]
                            },
                            {
                                "ctitle":"男士内搭",
                                "ccontent":[
                                    {
                                        "img":"static/2 (1).jpg",
                                        "title":"衬衫"
                                    },
                                    {
                                        "img":"static/rBACVF2jzNyAMrmQAAHaOSE2_0M377_360x360.jpg",
                                        "title":"T恤"
                                    },
                                    {
                                        "img":"static/1 (3).jpg",
                                        "title":"针织衫"
                                    },
                                    {
                                        "img":"static/2 (3).jpg",
                                        "title":"POLO衫"
                                    },
                                    {
                                        "img":"static/2 (8).jpg",
                                        "title":"卫衣"
                                    },
                                    {
                                        "img":"static/2 (9).jpg",
                                        "title":"马甲"
                                    },
                                ]
                            },
                            {
                                "ctitle":"男士下装",
                                "ccontent":[
                                    {
                                        "img":"static/2 (10).jpg",
                                        "title":"休闲裤"
                                    },
                                    {
                                        "img":"static/2 (13).jpg",
                                        "title":"牛仔裤"
                                    },
                                    {
                                        "img":"static/2 (12).jpg",
                                        "title":"西裤"
                                    },
                                    {
                                        "img":"static/2 (6).jpg",
                                        "title":"短裤"
                                    },
                                ]
                            },
                        ]
                    }
                },
                {
                    "title":"女装",
                    "content":{
                        "smallTitle":"女装",
                        "clothes":[
                            {
                                "ctitle":"外衣/套装",
                                "ccontent":[
                                    {
                                        "img":"static/3 (19).jpg",
                                        "title":"羽绒服/棉服"
                                    },
                                    {
                                        "img":"static/3 (20).jpg",
                                        "title":"外套马甲"
                                    },
                                    {
                                        "img":"static/rBACW12hPEGAM4VRAAcK341vpS8148_360x360.jpg",
                                        "title":"风衣/大衣"
                                    },
                                    {
                                        "img":"static/3 (1).jpg",
                                        "title":"皮衣皮革"
                                    },
                                ]
                            },
                            {
                                "ctitle":"女士内搭",
                                "ccontent":[
                                    {
                                        "img":"static/3 (4).jpg",
                                        "title":"羊绒羊毛衫"
                                    },
                                    {
                                        "img":"static/rBACW12DMtCAG6C7AARr7fMn99g676_360x360.jpg",
                                        "title":"针织衫"
                                    },
                                    {
                                        "img":"static/3 (6).jpg",
                                        "title":"连衣裙"
                                    },
                                    {
                                        "img":"static/3 (13).jpg",
                                        "title":"卫衣"
                                    },
                                    {
                                        "img":"static/3 (3).jpg",
                                        "title":"衬衫/雪纺"
                                    },
                                    {
                                        "img":"static/3 (10).jpg",
                                        "title":"T恤/吊带"
                                    },
                                ]
                            },
                            {
                                "ctitle":"女士下装",
                                "ccontent":[
                                    {
                                        "img":"static/rBACYV2F8SiALZWGAAfcprdVqFw590_360x360.jpg",
                                        "title":"休闲裤"
                                    },
                                    {
                                        "img":"static/3 (11).jpg",
                                        "title":"牛仔裤"
                                    },
                                    {
                                        "img":"static/3 (17).jpg",
                                        "title":"半身裙"
                                    },
                                    {
                                        "img":"static/rBACW12RZFuAOrOWAAcKz0OKN84194_360x360.jpg",
                                        "title":"短裤"
                                    },
                                ]
                            },
                        ]
                    }
                },
                {
                    "title":"美妆",
                    "content":{
                        "smallTitle":"美妆",
                        "clothes":[
                            {
                                "ctitle":"面部护理",
                                "ccontent":[
                                    {
                                        "img":"static/4 (1).jpg",
                                        "title":"乳液面膜"
                                    },
                                    {
                                        "img":"static/4 (2).jpg",
                                        "title":"精华"
                                    },
                                    {
                                        "img":"static/4 (3).jpg",
                                        "title":"化妆水"
                                    },
                                    {
                                        "img":"static/4 (4).jpg",
                                        "title":"洁面/卸妆"
                                    },
                                    {
                                        "img":"static/4 (14).jpg",
                                        "title":"面膜"
                                    },
                                    {
                                        "img":"static/4 (6).jpg",
                                        "title":"颈部护理"
                                    },
                                ]
                            },
                            {
                                "ctitle":"香水彩妆",
                                "ccontent":[
                                    {
                                        "img":"static/4 (7).jpg",
                                        "title":"底妆"
                                    },
                                    {
                                        "img":"static/4 (17).jpg",
                                        "title":"唇妆"
                                    },
                                    {
                                        "img":"static/4 (6).jpg",
                                        "title":"眼妆"
                                    },
                                    {
                                        "img":"static/4 (15).jpg",
                                        "title":"美妆工具"
                                    },
                                    {
                                        "img":"static/4 (13).jpg",
                                        "title":"香水/美甲"
                                    },
                                ]
                            },
                        ]
                    }
                },
                {
                    "title":"个护",
                    "content":{
                        "smallTitle":"个护",
                        "clothes":[
                            {
                                "ctitle":"身体护理",
                                "ccontent":[
                                    {
                                        "img":"static/4 (16).jpg",
                                        "title":"洗发护发"
                                    },
                                    {
                                        "img":"static/4 (6).jpg",
                                        "title":"沐浴护肤"
                                    },
                                    {
                                        "img":"static/rBACYV1fUr-Ae42IAAnc8jkFDFc764_360x360.jpg",
                                        "title":"手足护理"
                                    },
                                    {
                                        "img":"static/4 (3).jpg",
                                        "title":"精油"
                                    },
                                    {
                                        "img":"static/rBACYVsBkiCAQtknAAAeqkThV_Q769.jpg",
                                        "title":"脱毛用品"
                                    },
                                ]
                            },
                            {
                                "ctitle":"男士护理",
                                "ccontent":[
                                    {
                                        "img":"static/4 (14).jpg",
                                        "title":"男士护肤"
                                    },
                                    {
                                        "img":"static/rBACW12R7daAfiHrAARVCEXoGog907_360x360.jpg",
                                        "title":"剃须刀"
                                    },
                                ]
                            },

                            {
                                "ctitle":"清洁/祛味",
                                "ccontent":[
                                    {
                                        "img":"static/rBACW10Ul4KAIC4tAABxUZ9669w081.jpg",
                                        "title":"家庭清洁"
                                    },
                                    {
                                        "img":"static/rBACVF1Tr2SAedGEAAQoLYzjMqg727_360x360.jpg",
                                        "title":"清洁工具"
                                    },
                                    {
                                        "img":"static/4 (10).jpg",
                                        "title":"香薰/祛味"
                                    },
                                    {
                                        "img":"static/rBACW126fRqAfa1cAAC-kEkUMsY266_360x360.jpg",
                                        "title":"纸品/棉棒"
                                    },
                                ]
                            },
                        ]
                    }
                },
                {
                    "title":"内衣配饰",
                    "content":{
                        "smallTitle":"内衣配饰",
                        "clothes":[
                            {
                                "ctitle":"内衣",
                                "ccontent":[
                                    {
                                        "img":"static/3 (7).jpg",
                                        "title":"文胸/吊带"
                                    },
                                    {
                                        "img":"static/2 (12).jpg",
                                        "title":"男士打底"
                                    },
                                    {
                                        "img":"static/2 (4).jpg",
                                        "title":"睡衣/家居服"
                                    },
                                    {
                                        "img":"static/rBACVF2nKRKALOcxAAIawjMRgN0999_360x360.jpg",
                                        "title":"女士内裤"
                                    },
                                    {
                                        "img":"static/3 (18).jpg",
                                        "title":"保暖衣裤"
                                    },
                                    {
                                        "img":"static/3 (10).jpg",
                                        "title":"塑身内衣"
                                    },
                                ]
                            },
                            {
                                "ctitle":"袜子",
                                "ccontent":[
                                    {
                                        "img":"static/rBACYV22Wr2AFtB8AA0h0-8FYko496_360x360.jpg",
                                        "title":"棉袜"
                                    },
                                    {
                                        "img":"static/3 (16).jpg",
                                        "title":"丝袜/裤袜"
                                    },
                                ]
                            },

                            {
                                "ctitle":"配饰",
                                "ccontent":[
                                    {
                                        "img":"static/4 (4).jpg",
                                        "title":"腰带/礼盒"
                                    },
                                    {
                                        "img":"static/rBACW12LJGuAMqbDAAEc_Gw0610758_360x360.jpg",
                                        "title":"围巾/方巾"
                                    },
                                    {
                                        "img":"static/rBACW12DMtCAG6C7AARr7fMn99g676_360x360.jpg",
                                        "title":"手套/帽子"
                                    },
                                    {
                                        "img":"static/rBACVFr449qAKeDvAABxxHpKBCE586.jpg",
                                        "title":"遮阳/雨伞"
                                    },
                                    {
                                        "img":"static/rBACYV2dS0eAQOlGAAd5qKsLoNQ113_360x360.jpg",
                                        "title":"领带"
                                    },
                                ]
                            },
                        ]
                    }
                },
                {
                    "title":"家纺",
                    "content":{
                        "smallTitle":"家纺",
                        "clothes":[
                            {
                                "ctitle":"家纺",
                                "ccontent":[
                                    {
                                        "img":"static/rBACVF1o5kWAaqfHAAbrslpPfyQ508_360x360.jpg",
                                        "title":"枕头枕芯"
                                    },
                                    {
                                        "img":"static/4 (18).jpg",
                                        "title":"床品套件"
                                    },
                                    {
                                        "img":"static/rBACYV22Wr2AFtB8AA0h0-8FYko496_360x360.jpg",
                                        "title":"垫毯/拖鞋"
                                    },
                                    {
                                        "img":"static/4 (20).jpg",
                                        "title":"毛浴巾/浴衣"
                                    },
                                    {
                                        "img":"static/4 (21).jpg",
                                        "title":"被子被芯"
                                    },
                                    {
                                        "img":"static/4 (20).jpg",
                                        "title":"床垫/床褥"
                                    },
                                    {
                                        "img":"static/4 (19).jpg",
                                        "title":"毯子/凉席"
                                    },
                                    {
                                        "img":"static/rBACVFtyMuqAJYZ3AACcR2Yf4PQ442.jpg",
                                        "title":"坐垫/抱枕"
                                    },
                                    {
                                        "img":"static/4 (20).jpg",
                                        "title":"窗帘/窗纱"
                                    },
                                ]
                            },
                            {
                                "ctitle":"生活用品",
                                "ccontent":[
                                    {
                                        "img":"static/rBACW11JRQ2AdzZwAApCAcPHrOw801_360x360.jpg",
                                        "title":"收纳用品"
                                    },
                                    {
                                        "img":"static/rBACW12RZ5GAQMFmAAI0qDa26Qg145_360x360.jpg",
                                        "title":"晾衣架/洗衣袋"
                                    },
                                    {
                                        "img":"static/rBACW11xvbuAcnFkAA5RIg49Qfc411_360x360.jpg",
                                        "title":"窗帘/窗纱"
                                    },
                                ]
                            },
                        ]
                    }
                },
                {
                    "title":"餐厨",
                    "content":{
                        "smallTitle":"餐厨",
                        "clothes":[
                            {
                                "ctitle":"厨具",
                                "ccontent":[
                                    {
                                        "img":"static/rBACW12RZ5GAQMFmAAI0qDa26Qg145_360x360.jpg",
                                        "title":"清洁收纳"
                                    },
                                    {
                                        "img":"static/rBACYVydnECAVMLkAAB5n8SFhcY662.jpg",
                                        "title":"刀具菜板"
                                    },
                                    {
                                        "img":"static/rBACYVsBkiCAQtknAAAeqkThV_Q769.jpg",
                                        "title":"餐具/筷子"
                                    },
                                    {
                                        "img":"static/rBACYV2ao3iAVig7AAPqu_bqZ1w428_360x360.jpg",
                                        "title":"烹饪锅具"
                                    },
                                    {
                                        "img":"static/rBACYV0R57yAR12kAABpCuxsAio010.jpg",
                                        "title":"厨房配件"
                                    },
                                ]
                            },
                            {
                                "ctitle":"水具/茶具",
                                "ccontent":[
                                    {
                                        "img":"static/rBACW12wL2KAC2t8AAGoAtCX52Q182_360x360.jpg",
                                        "title":"保温杯壶"
                                    },
                                    {
                                        "img":"static/rBACW12SBiuAWGriAAepwoZ13Co558_360x360.jpg",
                                        "title":"茶具/酒具"
                                    },
                                    {
                                        "img":"static/rBACVF1aZD2AUHF-AAYbOMNfa1E090_360x360.jpg",
                                        "title":"咖啡杯具"
                                    },
                                ]
                            },
                        ]
                    }
                },
                {
                    "title":"电器",
                    "content":{
                        "smallTitle":"电器",
                        "clothes":[
                            {
                                "ctitle":"个护健康",
                                "ccontent":[
                                    {
                                        "img":"static/4 (14).jpg",
                                        "title":"面部护理"
                                    },
                                    {
                                        "img":"static/4 (8).jpg",
                                        "title":"美发护理"
                                    },
                                    {
                                        "img":"static/4 (4).jpg",
                                        "title":"口腔护理"
                                    },
                                    {
                                        "img":"static/rBACYV2ao3iAVig7AAPqu_bqZ1w428_360x360.jpg",
                                        "title":"按摩器"
                                    },
                                ]
                            },
                            {
                                "ctitle":"厨用电器",
                                "ccontent":[
                                    {
                                        "img":"static/rBACVFvw09eAF_35AABTSQ1y-_w892.jpg",
                                        "title":"烹饪电器"
                                    },
                                    {
                                        "img":"static/rBACVF0mrkeAOu-xAABNEqh8CyA185.jpg",
                                        "title":"水壶"
                                    },
                                    {
                                        "img":"static/rBACVF3A5_SARb5pAAU2tZj4kQI592_360x360.jpg",
                                        "title":"榨汁机"
                                    },
                                    {
                                        "img":"static/rBACW12R7daAfiHrAARVCEXoGog907_360x360.jpg",
                                        "title":"咖啡机"
                                    },
                                    {
                                        "img":"static/rBACVF1aZD2AUHF-AAYbOMNfa1E090_360x360.jpg",
                                        "title":"保鲜/计量"
                                    },
                                ]
                            },
                        ]
                    }
                },
                {
                    "title":"饮食",
                    "content":{
                        "smallTitle":"饮食",
                        "clothes":[
                            {
                                "ctitle":"休食",
                                "ccontent":[
                                    {
                                        "img":"static/5 (1).jpg",
                                        "title":"糕点/小食"
                                    },
                                    {
                                        "img":"static/5 (2).jpg",
                                        "title":"巧克力/糖果"
                                    },
                                    {
                                        "img":"static/5 (3).jpg",
                                        "title":"肉干肉松"
                                    },
                                    {
                                        "img":"static/5 (16).jpg",
                                        "title":"坚果炒货"
                                    },
                                    {
                                        "img":"static/5 (4).jpg",
                                        "title":"卤味"
                                    },
                                    {
                                        "img":"static/5 (7).jpg",
                                        "title":"蜜饯果干"
                                    },
                                    {
                                        "img":"static/5 (11).jpg",
                                        "title":"腊味"
                                    },
                                ]
                            },
                            {
                                "ctitle":"茶饮/冲调",
                                "ccontent":[
                                    {
                                        "img":"static/5 (10).jpg",
                                        "title":"传统滋补"
                                    },
                                    {
                                        "img":"static/rBACW12SBiuAWGriAAepwoZ13Co558_360x360.jpg",
                                        "title":"茗茶"
                                    },
                                    {
                                        "img":"static/4 (11).jpg",
                                        "title":"花茶/果茶"
                                    },
                                    {
                                        "img":"static/5 (7).jpg",
                                        "title":"果汁饮料"
                                    },
                                ]
                            },
                        ]
                    }
                },
                {
                    "title":"箱包",
                    "content":{
                        "smallTitle":"箱包",
                        "clothes":[
                            {
                                "ctitle":"男士包袋",
                                "ccontent":[
                                    {
                                        "img":"static/7 (1).jpg",
                                        "title":"男士钱包卡包"
                                    },
                                    {
                                        "img":"static/7 (8).jpg",
                                        "title":"男士背包"
                                    },
                                    {
                                        "img":"static/7 (9).jpg",
                                        "title":"男士商务包"
                                    },
                                    {
                                        "img":"static/7 (6).jpg",
                                        "title":"男士钥匙扣"
                                    },
                                ]
                            },
                            {
                                "ctitle":"功能箱包",
                                "ccontent":[
                                    {
                                        "img":"static/7 (10).jpg",
                                        "title":"拉杆箱"
                                    },
                                    {
                                        "img":"static/7 (5).jpg",
                                        "title":"休闲/功能包"
                                    },
                                    {
                                        "img":"static/7 (3).jpg",
                                        "title":"妈咪包"
                                    },
                                ]
                            },
                            {
                                "ctitle":"时尚女包",
                                "ccontent":[
                                    {
                                        "img":"static/7 (9).jpg",
                                        "title":"女士单肩包"
                                    },
                                    {
                                        "img":"static/7 (4).jpg",
                                        "title":"女士钱包手包"
                                    },
                                ]
                            },
                        ]
                    }
                },
                {
                    "title":"鞋靴",
                    "content":{
                        "smallTitle":"鞋靴",
                        "clothes":[
                            {
                                "ctitle":"男鞋",
                                "ccontent":[
                                    {
                                        "img":"static/6 (8).jpg",
                                        "title":"男士休闲"
                                    },
                                    {
                                        "img":"static/6 (1).jpg",
                                        "title":"男士商务"
                                    },
                                    {
                                        "img":"static/6 (11).jpg",
                                        "title":"男士工装鞋"
                                    },
                                    {
                                        "img":"static/6 (5).jpg",
                                        "title":"男士板鞋"
                                    },
                                    {
                                        "img":"static/6 (2).jpg",
                                        "title":"男靴"
                                    },
                                    {
                                        "img":"static/6 (9).jpg",
                                        "title":"男士豆豆鞋"
                                    },
                                    {
                                        "img":"static/6 (4).jpg",
                                        "title":"男士凉鞋"
                                    },
                                ]
                            },
                            {
                                "ctitle":"女鞋",
                                "ccontent":[
                                    {
                                        "img":"static/6 (7).jpg",
                                        "title":"女靴"
                                    },
                                    {
                                        "img":"static/3 (15).jpg",
                                        "title":"女士单鞋"
                                    },
                                    {
                                        "img":"static/6 (3).jpg",
                                        "title":"女士休闲"
                                    },
                                    {
                                        "img":"static/6 (8).jpg",
                                        "title":"女士板鞋"
                                    },
                                    {
                                        "img":"static/6 (11).jpg",
                                        "title":"女士工装鞋"
                                    },
                                    {
                                        "img":"static/6 (4).jpg",
                                        "title":"女士拖鞋"
                                    },
                                    {
                                        "img":"static/6 (10).jpg",
                                        "title":"女士雪地靴"
                                    },
                                    {
                                        "img":"static/1 (6).jpg",
                                        "title":"女士凉鞋"
                                    },
                                ]
                            },
                        ]
                    }
                },
                {
                    "title":"母婴",
                    "content":{
                        "smallTitle":"母婴",
                        "clothes":[
                            {
                                "ctitle":"婴儿用品",
                                "ccontent":[
                                    {
                                        "img":"static/rBACW10Ul4KAIC4tAABxUZ9669w081.jpg",
                                        "title":"尿裤湿巾"
                                    },
                                    {
                                        "img":"static/rBACW12DMtCAG6C7AARr7fMn99g676_360x360.jpg",
                                        "title":"洗护用品"
                                    },
                                    {
                                        "img":"static/rBACYV1fUr-Ae42IAAnc8jkFDFc764_360x360.jpg",
                                        "title":"婴儿服饰"
                                    },
                                    {
                                        "img":"static/rBACYV1sp42ACoWMAAUr_8OZJog264_360x360.jpg",
                                        "title":"安全防护"
                                    },
                                    {
                                        "img":"static/rBACYV1sp42ACoWMAAUr_8OZJog264_360x360.jpg",
                                        "title":"婴儿寝居"
                                    },
                                    {
                                        "img":"static/rBACYV1sp42ACoWMAAUr_8OZJog264_360x360.jpg",
                                        "title":"喂养用品"
                                    },
                                ]
                            },
                            {
                                "ctitle":"童装童靴",
                                "ccontent":[
                                    {
                                        "img":"static/rBACW10Ul4KAIC4tAABxUZ9669w081.jpg",
                                        "title":"童鞋"
                                    },
                                    {
                                        "img":"static/rBACW12DMtCAG6C7AARr7fMn99g676_360x360.jpg",
                                        "title":"童装"
                                    },
                                    {
                                        "img":"static/rBACW12DMtCAG6C7AARr7fMn99g676_360x360.jpg",
                                        "title":"童袜"
                                    },
                                    {
                                        "img":"static/rBACW12DMtCAG6C7AARr7fMn99g676_360x360.jpg",
                                        "title":"内衣睡衣"
                                    },
                                    {
                                        "img":"static/rBACW12DMtCAG6C7AARr7fMn99g676_360x360.jpg",
                                        "title":"亲子"
                                    },
                                ]
                            },

                            {
                                "ctitle":"儿童用品",
                                "ccontent":[
                                    {
                                        "img":"static/rBACW10Ul4KAIC4tAABxUZ9669w081.jpg",
                                        "title":"儿童玩具"
                                    },
                                    {
                                        "img":"static/rBACW12DMtCAG6C7AARr7fMn99g676_360x360.jpg",
                                        "title":"书包/文具"
                                    },
                                    {
                                        "img":"static/rBACW12DMtCAG6C7AARr7fMn99g676_360x360.jpg",
                                        "title":"儿童床品"
                                    },
                                    {
                                        "img":"static/rBACW12DMtCAG6C7AARr7fMn99g676_360x360.jpg",
                                        "title":"儿童床垫"
                                    },
                                    {
                                        "img":"static/rBACW12DMtCAG6C7AARr7fMn99g676_360x360.jpg",
                                        "title":"童车童床"
                                    },
                                    {
                                        "img":"static/rBACW12DMtCAG6C7AARr7fMn99g676_360x360.jpg",
                                        "title":"儿童拉杆箱"
                                    },
                                ]
                            },

                            {
                                "ctitle":"妈妈专区",
                                "ccontent":[
                                    {
                                        "img":"static/rBACW10Ul4KAIC4tAABxUZ9669w081.jpg",
                                        "title":"产妇用品"
                                    },
                                    {
                                        "img":"static/rBACW12DMtCAG6C7AARr7fMn99g676_360x360.jpg",
                                        "title":"奶包/腰凳"
                                    },
                                ]
                            },
                        ]
                    }
                },
                {
                    "title":"眼镜",
                    "content":{
                        "smallTitle":"眼镜",
                        "clothes":[
                            {
                                "ctitle":"眼镜",
                                "ccontent":[
                                    {
                                        "img":"static/rBACW10Ul4KAIC4tAABxUZ9669w081.jpg",
                                        "title":"近视/老花镜"
                                    },
                                    {
                                        "img":"static/rBACW12DMtCAG6C7AARr7fMn99g676_360x360.jpg",
                                        "title":"隐形眼镜"
                                    },
                                    {
                                        "img":"static/rBACYV1fUr-Ae42IAAnc8jkFDFc764_360x360.jpg",
                                        "title":"太阳镜"
                                    },
                                    {
                                        "img":"static/rBACYV1sp42ACoWMAAUr_8OZJog264_360x360.jpg",
                                        "title":"运动眼镜"
                                    },
                                    {
                                        "img":"static/rBACYV1sp42ACoWMAAUr_8OZJog264_360x360.jpg",
                                        "title":"儿童眼镜"
                                    },
                                ]
                            },
                        ]
                    }
                },
                {
                    "title":"数码",
                    "content":{
                        "smallTitle":"数码",
                        "clothes":[
                            {
                                "ctitle":"影音充电",
                                "ccontent":[
                                    {
                                        "img":"static/rBACW10Ul4KAIC4tAABxUZ9669w081.jpg",
                                        "title":"影音娱乐"
                                    },
                                    {
                                        "img":"static/rBACW12DMtCAG6C7AARr7fMn99g676_360x360.jpg",
                                        "title":"充电设备"
                                    },
                                    {
                                        "img":"static/rBACYV1fUr-Ae42IAAnc8jkFDFc764_360x360.jpg",
                                        "title":"摄影配件"
                                    },
                                ]
                            },

                            {
                                "ctitle":"外设办公",
                                "ccontent":[
                                    {
                                        "img":"static/rBACW10Ul4KAIC4tAABxUZ9669w081.jpg",
                                        "title":"支架"
                                    },
                                    {
                                        "img":"static/rBACW12DMtCAG6C7AARr7fMn99g676_360x360.jpg",
                                        "title":"数码办公"
                                    },
                                    {
                                        "img":"static/rBACYV1fUr-Ae42IAAnc8jkFDFc764_360x360.jpg",
                                        "title":"数码配件"
                                    },
                                    {
                                        "img":"static/rBACYV1fUr-Ae42IAAnc8jkFDFc764_360x360.jpg",
                                        "title":"数据线"
                                    },
                                ]
                            },
                        ]
                    }
                },
                {
                    "title":"运动",
                    "content":{
                        "smallTitle":"运动",
                        "clothes":[
                            {
                                "ctitle":"运动鞋靴",
                                "ccontent":[
                                    {
                                        "img":"static/rBACW10Ul4KAIC4tAABxUZ9669w081.jpg",
                                        "title":"休闲鞋"
                                    },
                                    {
                                        "img":"static/rBACW12DMtCAG6C7AARr7fMn99g676_360x360.jpg",
                                        "title":"跑鞋"
                                    },
                                    {
                                        "img":"static/rBACYV1fUr-Ae42IAAnc8jkFDFc764_360x360.jpg",
                                        "title":"训练鞋"
                                    },
                                    {
                                        "img":"static/rBACYV1fUr-Ae42IAAnc8jkFDFc764_360x360.jpg",
                                        "title":"户外鞋"
                                    },
                                ]
                            },

                            {
                                "ctitle":"运动服饰",
                                "ccontent":[
                                    {
                                        "img":"static/rBACW10Ul4KAIC4tAABxUZ9669w081.jpg",
                                        "title":"配饰袜子"
                                    },
                                    {
                                        "img":"static/rBACW12DMtCAG6C7AARr7fMn99g676_360x360.jpg",
                                        "title":"长裤健身服"
                                    },
                                    {
                                        "img":"static/rBACYV1fUr-Ae42IAAnc8jkFDFc764_360x360.jpg",
                                        "title":"卫衣套头衫"
                                    },
                                    {
                                        "img":"static/rBACYV1fUr-Ae42IAAnc8jkFDFc764_360x360.jpg",
                                        "title":"短裤T恤"
                                    },
                                    {
                                        "img":"static/rBACYV1fUr-Ae42IAAnc8jkFDFc764_360x360.jpg",
                                        "title":"夹克/外套"
                                    },
                                    {
                                        "img":"static/rBACYV1fUr-Ae42IAAnc8jkFDFc764_360x360.jpg",
                                        "title":"泳衣"
                                    },
                                ]
                            },

                            {
                                "ctitle":"户外服饰",
                                "ccontent":[
                                    {
                                        "img":"static/rBACW10Ul4KAIC4tAABxUZ9669w081.jpg",
                                        "title":"冲锋衣裤"
                                    },
                                    {
                                        "img":"static/rBACW12DMtCAG6C7AARr7fMn99g676_360x360.jpg",
                                        "title":"速干衣裤"
                                    },
                                ]
                            },

                            {
                                "ctitle":"运动装备",
                                "ccontent":[
                                    {
                                        "img":"static/rBACW10Ul4KAIC4tAABxUZ9669w081.jpg",
                                        "title":"户外装备"
                                    },
                                    {
                                        "img":"static/rBACW12DMtCAG6C7AARr7fMn99g676_360x360.jpg",
                                        "title":"体育用品"
                                    },
                                ]
                            },
                        ]
                    }
                },
                {
                    "title":"家装",
                    "content":{
                        "smallTitle":"家装",
                        "clothes":[
                            {
                                "ctitle":"厨卫用品",
                                "ccontent":[
                                    {
                                        "img":"static/rBACW10Ul4KAIC4tAABxUZ9669w081.jpg",
                                        "title":"厨卫配件"
                                    },
                                    {
                                        "img":"static/rBACW12DMtCAG6C7AARr7fMn99g676_360x360.jpg",
                                        "title":"花洒"
                                    },
                                    {
                                        "img":"static/rBACYV1fUr-Ae42IAAnc8jkFDFc764_360x360.jpg",
                                        "title":"龙头/水槽"
                                    },
                                    {
                                        "img":"static/rBACYV1fUr-Ae42IAAnc8jkFDFc764_360x360.jpg",
                                        "title":"马桶/马桶盖"
                                    },
                                    {
                                        "img":"static/rBACYV1fUr-Ae42IAAnc8jkFDFc764_360x360.jpg",
                                        "title":"浴柜/浴霸"
                                    },
                                    {
                                        "img":"static/rBACYV1fUr-Ae42IAAnc8jkFDFc764_360x360.jpg",
                                        "title":"垃圾处理器"
                                    },
                                ]
                            },

                            {
                                "ctitle":"灯具",
                                "ccontent":[
                                    {
                                        "img":"static/rBACW10Ul4KAIC4tAABxUZ9669w081.jpg",
                                        "title":"吸顶灯"
                                    },
                                    {
                                        "img":"static/rBACW12DMtCAG6C7AARr7fMn99g676_360x360.jpg",
                                        "title":"台灯落地灯"
                                    },
                                    {
                                        "img":"static/rBACYV1fUr-Ae42IAAnc8jkFDFc764_360x360.jpg",
                                        "title":"户外灯"
                                    },
                                    {
                                        "img":"static/rBACYV1fUr-Ae42IAAnc8jkFDFc764_360x360.jpg",
                                        "title":"吊灯/水晶灯"
                                    },
                                ]
                            },

                            {
                                "ctitle":"家装软饰",
                                "ccontent":[
                                    {
                                        "img":"static/rBACW10Ul4KAIC4tAABxUZ9669w081.jpg",
                                        "title":"挂钟/摆件"
                                    },
                                    {
                                        "img":"static/rBACW12DMtCAG6C7AARr7fMn99g676_360x360.jpg",
                                        "title":"相框/装饰画"
                                    },
                                ]
                            },

                            {
                                "ctitle":"五金工具",
                                "ccontent":[
                                    {
                                        "img":"static/rBACW10Ul4KAIC4tAABxUZ9669w081.jpg",
                                        "title":"锁具"
                                    },
                                    {
                                        "img":"static/rBACW12DMtCAG6C7AARr7fMn99g676_360x360.jpg",
                                        "title":"小工具"
                                    },
                                    {
                                        "img":"static/rBACW12DMtCAG6C7AARr7fMn99g676_360x360.jpg",
                                        "title":"开关插座"
                                    },
                                ]
                            },
                        ]
                    }
                },
                {
                    "title":"正餐",
                    "content":{
                        "smallTitle":"正餐",
                        "clothes":[
                            {
                                "ctitle":"正餐",
                                "ccontent":[
                                    {
                                        "img":"static/rBACW10Ul4KAIC4tAABxUZ9669w081.jpg",
                                        "title":"罐头/酱菜"
                                    },
                                    {
                                        "img":"static/rBACW12DMtCAG6C7AARr7fMn99g676_360x360.jpg",
                                        "title":"川湘菜"
                                    },
                                    {
                                        "img":"static/rBACYV1fUr-Ae42IAAnc8jkFDFc764_360x360.jpg",
                                        "title":"江浙菜"
                                    },
                                    {
                                        "img":"static/rBACYV1fUr-Ae42IAAnc8jkFDFc764_360x360.jpg",
                                        "title":"主食"
                                    },
                                    {
                                        "img":"static/rBACYV1fUr-Ae42IAAnc8jkFDFc764_360x360.jpg",
                                        "title":"中西融合菜"
                                    },
                                    {
                                        "img":"static/rBACYV1fUr-Ae42IAAnc8jkFDFc764_360x360.jpg",
                                        "title":"日式料理"
                                    },
                                    {
                                        "img":"static/rBACYV1fUr-Ae42IAAnc8jkFDFc764_360x360.jpg",
                                        "title":"本帮菜"
                                    },
                                    {
                                        "img":"static/rBACYV1fUr-Ae42IAAnc8jkFDFc764_360x360.jpg",
                                        "title":"粤菜"
                                    },
                                    {
                                        "img":"static/rBACYV1fUr-Ae42IAAnc8jkFDFc764_360x360.jpg",
                                        "title":"鲁菜"
                                    },
                                ]
                            },

                            {
                                "ctitle":"家装软饰",
                                "ccontent":[
                                    {
                                        "img":"static/rBACW10Ul4KAIC4tAABxUZ9669w081.jpg",
                                        "title":"挂钟/摆件"
                                    },
                                    {
                                        "img":"static/rBACW12DMtCAG6C7AARr7fMn99g676_360x360.jpg",
                                        "title":"相框/装饰画"
                                    },
                                ]
                            },
                        ]
                    }
                },
                {
                    "title":"汽配",
                    "content":{
                        "smallTitle":"汽配",
                        "clothes":[
                            {
                                "ctitle":"汽车配件",
                                "ccontent":[
                                    {
                                        "img":"static/rBACW10Ul4KAIC4tAABxUZ9669w081.jpg",
                                        "title":"坐垫/脚垫"
                                    },
                                    {
                                        "img":"static/rBACW12DMtCAG6C7AARr7fMn99g676_360x360.jpg",
                                        "title":"腰靠颈枕"
                                    },
                                ]
                            },

                            {
                                "ctitle":"配饰清洁",
                                "ccontent":[
                                    {
                                        "img":"static/rBACW10Ul4KAIC4tAABxUZ9669w081.jpg",
                                        "title":"车载及周边"
                                    },
                                    {
                                        "img":"static/rBACW12DMtCAG6C7AARr7fMn99g676_360x360.jpg",
                                        "title":"汽车清洁"
                                    },
                                ]
                            },
                        ]
                    }
                },
            ]
        }
        return data
    }
}