
module.exports={
    gettypeData(){
        let data={
            "goodsList":[
                {
                    "title":"男装",
                    "content":{
                        "smallTitle":"男装",
                        "clothes":[
                            {
                                "ctitle":"男士外套",
                                "ccontent":[
                                    {
                                        "img":"static/rBACW10Ul4KAIC4tAABxUZ9669w081.jpg",
                                        "title":"羽绒/棉服"
                                    },
                                    {
                                        "img":"static/rBACW12DMtCAG6C7AARr7fMn99g676_360x360.jpg",
                                        "title":"皮衣/夹克"
                                    },
                                    {
                                        "img":"static/rBACYV1fUr-Ae42IAAnc8jkFDFc764_360x360.jpg",
                                        "title":"风衣/大衣"
                                    },
                                    {
                                        "img":"static/rBACYV1sp42ACoWMAAUr_8OZJog264_360x360.jpg",
                                        "title":"西服套装"
                                    },
                                ]
                            },
                            {
                                "ctitle":"男士内搭",
                                "ccontent":[
                                    {
                                        "img":"static/rBACW10Ul4KAIC4tAABxUZ9669w081.jpg",
                                        "title":"衬衫"
                                    },
                                    {
                                        "img":"static/rBACW12DMtCAG6C7AARr7fMn99g676_360x360.jpg",
                                        "title":"T恤"
                                    },
                                    {
                                        "img":"static/rBACYV1fUr-Ae42IAAnc8jkFDFc764_360x360.jpg",
                                        "title":"针织衫"
                                    },
                                    {
                                        "img":"static/rBACYV1sp42ACoWMAAUr_8OZJog264_360x360.jpg",
                                        "title":"POLO衫"
                                    },
                                    {
                                        "img":"static/rBACYV1sp42ACoWMAAUr_8OZJog264_360x360.jpg",
                                        "title":"卫衣"
                                    },
                                    {
                                        "img":"static/rBACYV1sp42ACoWMAAUr_8OZJog264_360x360.jpg",
                                        "title":"马甲"
                                    },
                                ]
                            },
                            {
                                "ctitle":"男士下装",
                                "ccontent":[
                                    {
                                        "img":"static/rBACW10Ul4KAIC4tAABxUZ9669w081.jpg",
                                        "title":"休闲裤"
                                    },
                                    {
                                        "img":"static/rBACW12DMtCAG6C7AARr7fMn99g676_360x360.jpg",
                                        "title":"牛仔裤"
                                    },
                                    {
                                        "img":"static/rBACYV1fUr-Ae42IAAnc8jkFDFc764_360x360.jpg",
                                        "title":"西裤"
                                    },
                                    {
                                        "img":"static/rBACYV1sp42ACoWMAAUr_8OZJog264_360x360.jpg",
                                        "title":"短裤"
                                    },
                                ]
                            },
                        ]
                    }
                },
                {
                    "title":"女装",
                    "content":{
                        "smallTitle":"女装",
                        "clothes":[
                            {
                                "c-title":"外衣/套装",
                                "c-content":[
                                    {
                                        "img":"static/rBACW10Ul4KAIC4tAABxUZ9669w081.jpg",
                                        "title":"羽绒服/棉服"
                                    },
                                    {
                                        "img":"static/rBACW12DMtCAG6C7AARr7fMn99g676_360x360.jpg",
                                        "title":"外套马甲"
                                    },
                                    {
                                        "img":"static/rBACYV1fUr-Ae42IAAnc8jkFDFc764_360x360.jpg",
                                        "title":"风衣/大衣"
                                    },
                                    {
                                        "img":"static/rBACYV1sp42ACoWMAAUr_8OZJog264_360x360.jpg",
                                        "title":"皮衣皮革"
                                    },
                                ]
                            },
                            {
                                "c-title":"女士内搭",
                                "c-content":[
                                    {
                                        "img":"static/rBACW10Ul4KAIC4tAABxUZ9669w081.jpg",
                                        "title":"羊绒羊毛衫"
                                    },
                                    {
                                        "img":"static/rBACW12DMtCAG6C7AARr7fMn99g676_360x360.jpg",
                                        "title":"针织衫"
                                    },
                                    {
                                        "img":"static/rBACYV1fUr-Ae42IAAnc8jkFDFc764_360x360.jpg",
                                        "title":"连衣裙"
                                    },
                                    {
                                        "img":"static/rBACYV1sp42ACoWMAAUr_8OZJog264_360x360.jpg",
                                        "title":"卫衣"
                                    },
                                    {
                                        "img":"static/rBACYV1sp42ACoWMAAUr_8OZJog264_360x360.jpg",
                                        "title":"衬衫/雪纺"
                                    },
                                    {
                                        "img":"static/rBACYV1sp42ACoWMAAUr_8OZJog264_360x360.jpg",
                                        "title":"T恤/吊带"
                                    },
                                ]
                            },
                            {
                                "c-title":"女士下装",
                                "c-content":[
                                    {
                                        "img":"static/rBACW10Ul4KAIC4tAABxUZ9669w081.jpg",
                                        "title":"休闲裤"
                                    },
                                    {
                                        "img":"static/rBACW12DMtCAG6C7AARr7fMn99g676_360x360.jpg",
                                        "title":"牛仔裤"
                                    },
                                    {
                                        "img":"static/rBACYV1fUr-Ae42IAAnc8jkFDFc764_360x360.jpg",
                                        "title":"半身裙"
                                    },
                                    {
                                        "img":"static/rBACYV1sp42ACoWMAAUr_8OZJog264_360x360.jpg",
                                        "title":"短裤"
                                    },
                                ]
                            },
                        ]
                    }
                },

            ]
        }
        return data
    }
}