module.exports={
    gettypeData(){
        let data={
            "goodsList":[
                {
                    "title":"女士内搭",
                    "content":[
                        {
                            "img":"static/rBACW10Ul4KAIC4tAABxUZ9669w081.jpg",
                            "title":"连衣裙"
                        },
                        {
                            "img":"static/rBACW12DMtCAG6C7AARr7fMn99g676_360x360.jpg",
                            "title":"毛衣"
                        },
                        {
                            "img":"static/rBACYV1fUr-Ae42IAAnc8jkFDFc764_360x360.jpg",
                            "title":"外套"
                        },
                        {
                            "img":"static/rBACYV1sp42ACoWMAAUr_8OZJog264_360x360.jpg",
                            "title":"羽绒服"
                        },
                        {
                            "img":"static/rBACYV2Nyl-AMLF0AAsaYSW3lmU676_360x360.jpg",
                            "title":"外套"
                        },
                        {
                            "img":"static/rBACYV2RUBiAWvk2AAHbUqTHw8Q793_360x360.jpg",
                            "title":"T恤长袖"
                        }
                    ]
                },
                {
                    "title":"女士下装",
                    "content":[
                        {
                            "img":"static/rBACW10Ul4KAIC4tAABxUZ9669w081.jpg",
                            "title":"休闲裤"
                        },
                        {
                            "img":"static/rBACW12DMtCAG6C7AARr7fMn99g676_360x360.jpg",
                            "title":"牛仔裤"
                        },
                        {
                            "img":"static/rBACYV1fUr-Ae42IAAnc8jkFDFc764_360x360.jpg",
                            "title":"半身裙"
                        },
                        {
                            "img":"static/rBACYV1sp42ACoWMAAUr_8OZJog264_360x360.jpg",
                            "title":"短裤"
                        }
                    ]
                },
                {
                    "title":"外衣/套装",
                    "content":[
                        {
                            "img":"static/rBACW10Ul4KAIC4tAABxUZ9669w081.jpg",
                            "title":""
                        },
                        {
                            "img":"static/rBACW12DMtCAG6C7AARr7fMn99g676_360x360.jpg",
                            "title":"fsf"
                        },
                        {
                            "img":"static/rBACYV1fUr-Ae42IAAnc8jkFDFc764_360x360.jpg",
                            "title":"外套"
                        },
                        {
                            "img":"static/rBACYV1sp42ACoWMAAUr_8OZJog264_360x360.jpg",
                            "title":"羽绒服"
                        },
                        {
                            "img":"static/rBACYV2Nyl-AMLF0AAsaYSW3lmU676_360x360.jpg",
                            "title":"外套"
                        },
                        {
                            "img":"static/rBACYV2RUBiAWvk2AAHbUqTHw8Q793_360x360.jpg",
                            "title":"T恤长袖"
                        }
                    ]
                },

            ]
        }
        return data
    }
}